"""add: School Table

Revision ID: 3c415d69ef86
Revises: 66a8e985cf21
Create Date: 2025-02-08 00:07:59.026464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c415d69ef86"
down_revision: Union[str, None] = "66a8e985cf21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school",
        sa.Column("director_id", sa.Integer(), nullable=False),
        sa.Column("school_address", sa.String(length=128), nullable=False),
        sa.Column("school_description", sa.Text(), nullable=False),
        sa.Column("school_type", sa.String(length=128), nullable=True),
        sa.Column("school_phone", sa.String(length=21), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["users.id"],
            name=op.f("fk_school_director_id_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("school")
    # ### end Alembic commands ###
