"""Upd: Teacher table

Revision ID: f980e94d9e91
Revises: 1b78ba8dee51
Create Date: 2025-03-04 20:13:42.151490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f980e94d9e91"
down_revision: Union[str, None] = "1b78ba8dee51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teacher", sa.Column("subject_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_teacher_subject_id_subjects"),
        "teacher",
        "subjects",
        ["subject_id"],
        ["id"],
        ondelete="cascade",
    )
    op.drop_column("teacher", "subject")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teacher",
        sa.Column(
            "subject",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_teacher_subject_id_subjects"), "teacher", type_="foreignkey"
    )
    op.drop_column("teacher", "subject_id")
    # ### end Alembic commands ###
