"""Init: FriendShip Table

Revision ID: cde0b952f697
Revises: 0e7d57db31fd
Create Date: 2025-02-06 18:42:56.302179

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cde0b952f697"
down_revision: Union[str, None] = "0e7d57db31fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendship",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("friend_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", name="choicesstatus"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["users.id"],
            name=op.f("fk_friendship_friend_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_friendship_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "friend_id", name=op.f("pk_friendship")),
    )
    op.create_index(
        op.f("ix_friendship_friend_id"),
        "friendship",
        ["friend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_friendship_user_id"), "friendship", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friendship_user_id"), table_name="friendship")
    op.drop_index(op.f("ix_friendship_friend_id"), table_name="friendship")
    op.drop_table("friendship")
    # ### end Alembic commands ###
