"""Upd: School table, add name

Revision ID: f042a74af0b2
Revises: e978dc450ebe
Create Date: 2025-02-13 21:34:08.166759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f042a74af0b2"
down_revision: Union[str, None] = "e978dc450ebe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "school",
        sa.Column("school_name", sa.String(length=128), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("school", "school_name")
    # ### end Alembic commands ###
