"""SChoolSubjectTable

Revision ID: c45ea3d0c167
Revises: df396bc1b008
Create Date: 2025-03-27 13:49:30.988319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c45ea3d0c167"
down_revision: Union[str, None] = "df396bc1b008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_subject",
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("subject_name", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name=op.f("fk_school_subject_school_id_school"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school_subject")),
        sa.UniqueConstraint(
            "school_id", "subject_name", name="unique_school_subject"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("school_subject")
    # ### end Alembic commands ###
