"""Upd: delete useless row

Revision ID: f938983e992d
Revises: 57a7cfb032e3
Create Date: 2025-02-22 18:14:06.385154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f938983e992d"
down_revision: Union[str, None] = "57a7cfb032e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "day_of_week")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column(
            "day_of_week",
            postgresql.ENUM(
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday",
                name="choicesdayofweek",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
