"""Upd: Classrom table

Revision ID: 4f2fb494535b
Revises: f938983e992d
Create Date: 2025-02-28 17:13:47.080282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f2fb494535b"
down_revision: Union[str, None] = "f938983e992d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classrooms",
        sa.Column("year_of_graduation", sa.Date(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classrooms", "year_of_graduation")
    # ### end Alembic commands ###
