"""Upd: school table

Revision ID: 5093f6076a4a
Revises: 3c415d69ef86
Create Date: 2025-02-08 15:21:45.536240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5093f6076a4a"
down_revision: Union[str, None] = "3c415d69ef86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("school_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_school_id_school"),
        "users",
        "school",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_school_id_school"), "users", type_="foreignkey"
    )
    op.drop_column("users", "school_id")
    # ### end Alembic commands ###
