"""add: user_id for Application table

Revision ID: 66a8e985cf21
Revises: 21968038304e
Create Date: 2025-02-07 15:54:29.379428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66a8e985cf21"
down_revision: Union[str, None] = "21968038304e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_applications_user_id_users"),
        "applications",
        "users",
        ["user_id"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_applications_user_id_users"),
        "applications",
        type_="foreignkey",
    )
    op.drop_column("applications", "user_id")
    # ### end Alembic commands ###
