"""Upd: Invite Table

Revision ID: df396bc1b008
Revises: c1675cacbdd4
Create Date: 2025-03-15 15:40:31.232908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df396bc1b008"
down_revision: Union[str, None] = "c1675cacbdd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitation",
        sa.Column(
            "invite_role",
            sa.Enum(
                "platform_admin",
                "school_admin",
                "class_teacher",
                "teacher",
                "student",
                "user",
                name="choicesrole",
            ),
            server_default="student",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitation", "invite_role")
    # ### end Alembic commands ###
