"""Upd lessons

Revision ID: 8d0c6ebbda37
Revises: b3e81973b97b
Create Date: 2025-03-31 15:40:12.812663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d0c6ebbda37"
down_revision: Union[str, None] = "b3e81973b97b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons", sa.Column("school_subject_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_lessons_school_subject_id_school_subject"),
        "lessons",
        "school_subject",
        ["school_subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("uq_school_director_id"), "school", ["director_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_school_director_id"), "school", type_="unique")
    op.drop_constraint(
        op.f("fk_lessons_school_subject_id_school_subject"),
        "lessons",
        type_="foreignkey",
    )
    op.drop_column("lessons", "school_subject_id")
    # ### end Alembic commands ###
