"""Feat subject + schedule + lessons

Revision ID: e7c6ca09879f
Revises: 751860615dd2
Create Date: 2025-02-19 14:48:03.039824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7c6ca09879f"
down_revision: Union[str, None] = "751860615dd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday",
                name="choicesdayofweek",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name=op.f("fk_schedules_classroom_id_classrooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.drop_table("schedule")
    op.add_column(
        "lessons", sa.Column("schedule_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_lessons_schedule_id_schedules"),
        "lessons",
        "schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_lessons_schedule_id_schedules"), "lessons", type_="foreignkey"
    )
    op.drop_column("lessons", "schedule_id")
    op.create_table(
        "schedule",
        sa.Column(
            "classroom_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "day_of_week",
            postgresql.ENUM(
                "monday",
                "tuesday",
                "wednesday",
                "thursday",
                "friday",
                "saturday",
                "sunday",
                name="choicesdayofweek",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name="fk_schedule_classroom_id_classrooms",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_schedule"),
    )
    op.drop_table("schedules")
    # ### end Alembic commands ###
