"""feat classroms table

Revision ID: d042189c2740
Revises: 6a69177db848
Create Date: 2025-02-14 16:27:47.787629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d042189c2740"
down_revision: Union[str, None] = "6a69177db848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classrooms",
        sa.Column("class_teacher_id", sa.Integer(), nullable=False),
        sa.Column("class_name", sa.String(length=16), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_teacher_id"],
            ["users.id"],
            name=op.f("fk_classrooms_class_teacher_id_users"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name=op.f("fk_classrooms_school_id_school"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classrooms")),
    )
    op.add_column(
        "users", sa.Column("classroom_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_users_classroom_id_classrooms"),
        "users",
        "classrooms",
        ["classroom_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_classroom_id_classrooms"), "users", type_="foreignkey"
    )
    op.drop_column("users", "classroom_id")
    op.drop_table("classrooms")
    # ### end Alembic commands ###
