"""Table for invited users

Revision ID: 64f4af4c4ea8
Revises: d042189c2740
Create Date: 2025-02-16 16:38:28.040082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64f4af4c4ea8"
down_revision: Union[str, None] = "d042189c2740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitation",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=36), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP + INTERVAL '3 DAYS')"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "accepted", "canceled", name="choicesinvitestatus"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_invitation_user_id_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitation")),
    )
    op.create_index(
        op.f("ix_invitation_token"), "invitation", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitation_token"), table_name="invitation")
    op.drop_table("invitation")
    # ### end Alembic commands ###
