"""Upd: User Table

Revision ID: 6a69177db848
Revises: f042a74af0b2
Create Date: 2025-02-14 12:55:47.442616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a69177db848"
down_revision: Union[str, None] = "f042a74af0b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=128), nullable=False)
    )
    op.add_column(
        "users", sa.Column("middle_name", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=128), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "middle_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
