"""Feat subject + schedule + lessons

Revision ID: 751860615dd2
Revises: 841fdf1e0421
Create Date: 2025-02-19 14:36:00.418881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "751860615dd2"
down_revision: Union[str, None] = "841fdf1e0421"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_lessons_subject_id_subjects"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_lessons_teacher_id_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
    )
    op.drop_constraint(
        "fk_schedule_subject_id_subjects", "schedule", type_="foreignkey"
    )
    op.drop_column("schedule", "end_time")
    op.drop_column("schedule", "start_time")
    op.drop_column("schedule", "subject_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "subject_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "schedule",
        sa.Column(
            "start_time",
            postgresql.TIME(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schedule",
        sa.Column(
            "end_time", postgresql.TIME(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_schedule_subject_id_subjects",
        "schedule",
        "subjects",
        ["subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("lessons")
    # ### end Alembic commands ###
