"""Upd: schedule_date for schedule

Revision ID: 57a7cfb032e3
Revises: 7da2edc4de55
Create Date: 2025-02-22 18:06:27.709074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57a7cfb032e3"
down_revision: Union[str, None] = "7da2edc4de55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules", sa.Column("schedule_date", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "schedule_date")
    # ### end Alembic commands ###
