"""SChoolSubjectTableM2mV2

Revision ID: b3e81973b97b
Revises: 3a2443140254
Create Date: 2025-03-27 14:26:27.286325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3e81973b97b"
down_revision: Union[str, None] = "c45ea3d0c167"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classroom_subjects",
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name=op.f("fk_classroom_subjects_classroom_id_classrooms"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["school_subject.id"],
            name=op.f("fk_classroom_subjects_subject_id_school_subject"),
        ),
        sa.PrimaryKeyConstraint(
            "classroom_id", "subject_id", name=op.f("pk_classroom_subjects")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classroom_subjects")
    # ### end Alembic commands ###
