"""Upd: Subject table

Revision ID: 7da2edc4de55
Revises: 5a55ce990669
Create Date: 2025-02-20 20:58:57.029981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7da2edc4de55"
down_revision: Union[str, None] = "5a55ce990669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column("description", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjects", "description")
    # ### end Alembic commands ###
