"""delete useless table

Revision ID: 7f489c4f2577
Revises: 8d0c6ebbda37
Create Date: 2025-04-03 20:33:12.911498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f489c4f2577"
down_revision: Union[str, None] = "8d0c6ebbda37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_lessons_subject_id_subjects", "lessons", type_="foreignkey"
    )
    op.drop_column("lessons", "subject_id")
    op.drop_constraint(
        "fk_school_subject_school_id_school",
        "school_subject",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_school_subject_school_id_school"),
        "school_subject",
        "school",
        ["school_id"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_school_subject_school_id_school"),
        "school_subject",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_school_subject_school_id_school",
        "school_subject",
        "school",
        ["school_id"],
        ["id"],
    )
    op.add_column(
        "lessons",
        sa.Column(
            "subject_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_lessons_subject_id_subjects",
        "lessons",
        "subjects",
        ["subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
