"""Upd: Invitation invited_by

Revision ID: 5a55ce990669
Revises: e7c6ca09879f
Create Date: 2025-02-20 10:50:10.840812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a55ce990669"
down_revision: Union[str, None] = "e7c6ca09879f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitation", sa.Column("invited_by", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_invitation_invited_by_users"),
        "invitation",
        "users",
        ["invited_by"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_invitation_invited_by_users"),
        "invitation",
        type_="foreignkey",
    )
    op.drop_column("invitation", "invited_by")
    # ### end Alembic commands ###
