"""Add Role for User

Revision ID: 21968038304e
Revises: faa414b2e278
Create Date: 2025-02-07 15:36:55.922462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21968038304e"
down_revision: Union[str, None] = "faa414b2e278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("director_full_name", sa.String(length=128), nullable=False),
        sa.Column("director_phone", sa.String(length=21), nullable=False),
        sa.Column("director_email", sa.String(length=128), nullable=False),
        sa.Column("school_name", sa.String(length=128), nullable=False),
        sa.Column("school_address", sa.String(length=128), nullable=False),
        sa.Column("school_phone", sa.String(length=21), nullable=False),
        sa.Column("school_description", sa.Text(), nullable=False),
        sa.Column("school_type", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="choicesapplicationstatus",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("applications")
    # ### end Alembic commands ###
