"""Feat teacher_info table

Revision ID: 4e0ec6a9e3e8
Revises: 64f4af4c4ea8
Create Date: 2025-02-19 12:10:54.762479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e0ec6a9e3e8"
down_revision: Union[str, None] = "64f4af4c4ea8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_teacher_user_id_users"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher")),
        sa.UniqueConstraint("user_id", name=op.f("uq_teacher_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher")
    # ### end Alembic commands ###
